[package]
name = "laliga_scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3"
reqwest = { version = "0.12.5", default-features = false, features = ["rustls-tls"] }
scraper = "0.19.0"
tokio = { version = "1", features = ["full"] }
